### ISSUE TITLE
A right-aligned column still displays its header centered

### ISSUE THREAD

**Issue by UweKeim** [tabalinas/jsgrid#1017]
When setting a column to [`align: right`](http://js-grid.com/docs/#fields), the CSS of [the default theme](https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css) still says:

```css
.jsgrid-header-row .jsgrid-align-right { 
    text-align: center;
}
```
My expected behaviour is that the header is also right-aligned.

I'm unsure whether this was a design decision or is an error.

I solved it by defining my own override CSS:

```css
.jsgrid-align-right {
    text-align: right !important;
}
```

To reproduce the "issue", create a field definition with the "align" field set to "right".
