### ISSUE TITLE
Question : Is there a way to always display the pager ?

### ISSUE THREAD

**Issue by StefH** [tabalinas/jsgrid#129]
Is there a way to always display the pager, also when the number of items (2) is less then the paging size (10) or when there are no results found.

**Comment by tabalinas** [comment]
Actually, the pager is just hidden with css. You can easily show it whether with css `!important` or with jquery in `onRefreshed` callback.

```css
.jsgrid-pager-container {
    display: block !important;
}
```

See the fiddle with an example http://jsfiddle.net/tabalinas/L8ny4bqz/
