### ISSUE TITLE
How we can color a particular cell in jsgrid?

### ISSUE THREAD

**Issue by Div703** [tabalinas/jsgrid#163]

**Comment by tabalinas** [comment]
It depends on your scenario, but it can be done in different ways:

1. use `cellRenderer` property of the field http://js-grid.com/docs/#fields

2. attach class to the row with `rowClass`

```css
// color second cell in the particular row
.my-row-custom-class td:nth-child(2) {
    background: red;
}
```

3. set padding of td to 0 and render wrapping div with a background color with `itemTemplate`

Pretty sure there are much more alternatives.
