### ISSUE TITLE
I'm using pagination, Can I remove the scrollbar?

### ISSUE THREAD

**Issue by flyinmryan** [tabalinas/jsgrid#179]
Hi again,
     Is there a way to remove the scrollbar? 
Thanks

**Comment by tabalinas** [comment]
First remove `height` option, then the grid will be stretched by the content.

And remove scrollbars with the following css

```css
.jsgrid-grid-header,
.jsgrid-grid-body{
  overflow: auto;
}
```

See the example http://jsfiddle.net/tabalinas/967y0t7s/
