### ISSUE TITLE
Texts are unreadable in responsive layout

### ISSUE THREAD

**Issue by am2222** [tabalinas/jsgrid#450]
Hi,
When I resize layout texts of rows become unreadable,Is there any solutions for this?

thanks
![capture1](https://cloud.githubusercontent.com/assets/4707503/18997287/8a44d254-8740-11e6-9847-23232da7f69e.PNG)

**Comment by tabalinas** [comment]
For now you can easily fix this with the following css:

```css
.jsgrid-cell {
    overflow: hidden;
}
```
