### ISSUE TITLE
textarea to auto adjust size as it loads 

### ISSUE THREAD

**Issue by labregowski** [tabalinas/jsgrid#692]
Hi.
Is there a way to make the textarea adjust the height to its content as it loads? 
I am able to do it with this function, 

```
$('#tablegrid').on( ' clicked  select change keyup keydown paste cut', 'textarea', function (){
    $(this).height(0).height(this.scrollHeight);
}).find( 'textarea' ).change();
```
but the user needs to click it. It would be great to make this function work at the moment when jsgrid turns the text into a textarea. But I am not fainding which event I should call.
ANy ideas?
Thanks

**Comment by tabalinas** [comment]
Redefine `editTemplate` so that it sets the height of the control once value has been set (https://github.com/tabalinas/jsgrid/blob/master/src/fields/jsgrid.field.textarea.js#L23).
If you expect this behavior for multiple fields, just redefine it for the `textarea` field.

**Comment by alouali** [comment]
Hello,

I've had the same problem, this is my solution based on CSS animationstart hack (because the DOMNodeInserted and jQuery $(element).ready(...) are both DEPRECATED !!!) : 

1)  In your css, add the following :
```css
/*
 * CSS Animation hack to detect Node Insertion
 */

@keyframes nodeInserted {
    from { opacity: 0.99; }
    to { opacity: 1; }
}

.onappear {
    animation-duration: 0.001s;
    animation-name: nodeInserted;
} 
```

2) In your code something like : 
```js
pField.editTemplate = function(value) {
  let t = Object.getPrototypeOf(this).editTemplate.call(this, value);
  t.addClass("onappear"); 
  t.on("animationstart", (e => {
    e.target.style.height = (e.target.scrollHeight + 10) + "px";
  }));
  return t;
};
```
